""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Maintainer:
"       Ilias Stamatis <stamatis.iliass@gmail.com>
"
" Sections:
"       -> Plugins
"       -> General
"       -> Clipboard
"       -> Indentation and Formatting
"       -> Auto-closing
"       -> Whitespace
"       -> Vertical Line
"       -> Code Navigation
"       -> Windows
"       -> Highlight and Searching
"       -> Backup and Swap
"       -> Compile and Run Code
"       -> Code Snippets
"       -> Languages
"       -> Shell Command
"       -> Plugins Configuration
"
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Plugins {
    " The following 4 lines are required by the Vundle plugin manager
    set nocompatible                " be iMproved (must be first line)
    filetype off
    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin()

    " Let Vundle manage Vundle, required
    Plugin 'VundleVim/Vundle.vim'

    " Vim motions. This plugin is really awesome!
    " Usage: for example type <leader><leader>w and navigate quickly
    Plugin 'easymotion/vim-easymotion'

    " Toggle code comments on/off
    Plugin 'preservim/nerdcommenter'

    if v:version >= 703 && has('lua')
        " Code completion
        Plugin 'Shougo/neocomplete.vim'
    endif

    if executable('ctags')
        " Navigation via file tags
        " Usage: Open the side bar with <leader>tt (custom map)
        Plugin 'majutsushi/tagbar'
    endif

    " The molokai theme
    Plugin 'tomasr/molokai'

    call vundle#end()               " required
    filetype plugin indent on       " required, automatically detect file types
" }

" General {
    set title                       " set window title
    set encoding=utf-8

    if has('statusline') && has('cmdline_info')
        set laststatus=2            " always show a status line
        set ruler                   " show the ruler
        set rulerformat=%30(%=\:b%n%y%m%r%w\ %l,%c%V\ %P%)
    endif

    set number                      " line numbers on
    set backspace=2                 " backspace as it needs to be
    set scrolloff=3                 " minimum lines to keep above and below cursor
    set hidden                      " allow buffer switching without saving

    " Time out on key codes but not mappings.
    set notimeout
    set ttimeout
    set ttimeoutlen=10

    syntax on                       " enable syntax highlighting
    colorscheme molokai

    let loaded_matchparen = 1       " don't do paren matching

    " With a map leader it's possible to do extra key combinations.
    let mapleader = ","

    " Save typing and eliminate :Q style typos due to lazy holding shift.
    nnoremap ; :

    " Quick save.
    nnoremap <leader>w :w!<cr>

    " Wrapped lines goes down/up to next row, rather than next line in file.
    noremap j gj
    noremap k gk

    " Revert the functionality of ^ and 0
    noremap 0 g^
    noremap ^ g0

    " <Esc> is inconvinient as it requires stretching to the top of the keyboard.
    inoremap jk <Esc>

    " <Del> key is too far...
    inoremap <leader>d <Del>

    " Make sure Vim returns to the same line when you reopen a file.
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

    " For when you forget to sudo.. Really Write the file.
    cnoremap w!! w !sudo tee % >/dev/null
" }

" Clipboard {
    if has('clipboard')
        " I don't set clipboard=unnamedplus because vim will then copy to the
        " clipboard when deleting too, which I find annoying. In the way
        " I configure things below I can just yank without thinking which
        " register is the data copied to. I only have to think about registers
        " and where I am pasting from (clipboard or unnamed register) when
        " hitting p.

        " Let y copy both to the unnamed register *and* the X11 clipboard
        autocmd TextYankPost *
            \ if v:event.operator == 'y' && v:event.regname == '' |
            \     call setreg('+', v:event.regcontents, v:event.regtype) |
            \ endif

        " Yank from the cursor to the end of the line
        nnoremap Y y$

        " Use the following to paste from the clipboard
        nnoremap <leader>p "+p
        nnoremap <leader>P "+P
    endif
" }

" Indentation and Formatting {
    set tabstop=4                   " show tabs as 8 spaces
    set shiftwidth=4                " use indents of 8 spaces
    set shiftround                  " always round to multiple of 'shiftwidth'
    set softtabstop=4               " let backspace delete indent
    "set noexpandtab                 " tabs are tabs, not spaces
    set expandtab                   " tabs are spaces, not tabs
    set smarttab
    set formatoptions=qrn1
    set autoindent                  " indent at the same level of the previous line

    " Use Q for formatting the current paragraph or visually selected lines
    vmap Q gq
    nmap Q gqap
" }

" Auto-closing {
    " I only care about auto-closing brackets of code blocks
    function! s:CloseBracket()
        if getline('.') =~# '^\s*\(struct\|class\|enum\) '
            return "{\<CR>};\<Esc>O"
        else
            return "{\<CR>}\<Esc>O"
        endif
    endfunction

    inoremap <expr> {<CR> <SID>CloseBracket()

    " This is also useful for languages like C
    inoremap (; ();<left><left>
" }

" Whitespace {
    " Remove trailing whitespace when saving.
    autocmd BufWritePre * :%s/\s\+$//e

    " But don't remove trailing whitespace when explicitly requested.
    nnoremap <leader>no :autocmd! BufWritePre<cr>

    " Clear a line quickly.
    nnoremap <leader><space> ^D

    " Insert empty line above or below while staying in normal mode.
    nnoremap <leader>o :set paste<cr>m`o<Esc>``:set nopaste<cr>
    nnoremap <leader>O :set paste<cr>m`O<Esc>``:set nopaste<cr>
" }

" Vertical Line {
    if exists('+colorcolumn')
        " Automatically show the vertical line for files containing source code.
        autocmd FileType c,cpp,java,python,javascript set colorcolumn=80
    endif

    function! g:ToggleColorColumn()
        if(&colorcolumn == 0)
            set colorcolumn=80
        else
            set colorcolumn=0
        endif
    endfunc

    nnoremap <leader>l :call g:ToggleColorColumn()<cr>
" }

" Code Navigation {
    " Go to the start/end of the function that the cursor is currently inside.
    "
    " The following is supposed to work only in languages that use brackets
    " such as C, and the opening/closing bracket is in column 1 (first char).
    nnoremap <leader>s [[
    nnoremap <leader>e ][

    if has('cscope')
        " Look for a 'cscope.out' file starting from the current directory, going up to the root directory.
        let s:dirs = split(getcwd(), "/")
        while s:dirs != []
                let s:path = "/" . join(s:dirs, "/")
                if (filereadable(s:path . "/cscope.out"))
                        execute "cs add " . s:path . "/cscope.out " . s:path . " -v"
                        break
                endif
                let s:dirs = s:dirs[:-2]
        endwhile

        " Make CTRL-] search through cscope first, then ctags.
        set cscopetag

        " Hit 'CTRL-\' followed by one of the cscope search types below.
        " The result of the cscope search will be displayed in the current window.
        nmap <C-\>g :cs find g <C-R>=expand("<cword>")<CR><CR>
        nmap <C-\>s :cs find s <C-R>=expand("<cword>")<CR><CR>
        nmap <C-\>c :cs find c <C-R>=expand("<cword>")<CR><CR>
        nmap <C-\>a :cs find a <C-R>=expand("<cword>")<CR><CR>
        nmap <C-\>f :cs find f <C-R>=expand("<cfile>")<CR><CR>

        " Using 'CTRL-spacebar' then a search type makes the vim window split horizontally.
        " The search result will be displayed in the new window.
        nmap <C-@>g :vert scs find g <C-R>=expand("<cword>")<CR><CR>
        nmap <C-@>s :vert scs find s <C-R>=expand("<cword>")<CR><CR>
        nmap <C-@>c :vert scs find c <C-R>=expand("<cword>")<CR><CR>
        nmap <C-@>a :vert scs find a <C-R>=expand("<cfile>")<CR><CR>
        nmap <C-@>f :vert scs find f <C-R>=expand("<cfile>")<CR><CR>

        " The following is the most commonly used, so let's have an extra even easier mapping.
        nmap <C-@><C-@> :vert scs find g <C-R>=expand("<cword>")<CR><CR>
    endif
" }

" Windows {
    set splitbelow                  " when splitting put new window below of the current one
    set splitright                  " when splitting put new window to the right of the current one

    " Close window quickly.
    nnoremap <leader>q :q<cr>
    nnoremap <leader><leader>q :q!<cr>

    " Easier moving in windows.
    nnoremap <C-J> <C-W>j
    nnoremap <C-K> <C-W>k
    nnoremap <C-L> <C-W>l
    nnoremap <C-H> <C-W>h
" }

" Highlight and Searching {
    set incsearch                   " incremental search
    set hlsearch                    " highlight search terms
    set ignorecase                  " case insensitive search
    set smartcase                   " case sensitive only when a capital letter appears

    " Clear highlighted search.
    nnoremap <silent> <leader>/ :nohlsearch<cr>

    " Highlight word occurrences but do not jump to the next result.
    nnoremap <leader>* *N
" }

" Backup and Swap {
    set noswapfile              " turn swap off
    set backup                  " enable backups

    let directory = $HOME . "/.vim/backup/"
    execute "set backupdir=".directory

    " Create backup directory if it doesn't exist.
    if !isdirectory(directory)
        silent! execute "!mkdir -p ".directory
    endif
" }

" Compile and Run Code {
    " Run {
        autocmd FileType python,sh,bash,zsh nnoremap <leader>r :w<cr> :!clear; ./%<cr>
        autocmd FileType c,cpp nnoremap <leader>r :!clear; ./%:r<cr>
        autocmd FileType java nnoremap <leader>r :!clear; java %:r<cr>
    " }

    " Compile {
        autocmd FileType c,cpp,java nnoremap <leader>m :w<cr> :Shell clear; make<cr>
        autocmd FileType c nnoremap <leader>c9 :w<cr> :Shell gcc -O0 -Wall -W -pedantic -ggdb3 -o %:r %<cr>
        autocmd FileType cpp nnoremap <leader>c9 :w<cr> :Shell g++ -O0 -Wall -W -pedantic -ggdb3 -o %:r %<cr>
        autocmd FileType java nnoremap <leader>c9 :w<cr> :Shell javac %<cr>
    " }

    " Make file executable and reload it.
    nnoremap <leader>x :!chmod +x %<cr> :e %<cr>
" }

" Code Snippets {
    function! g:ExpandSnippet()
        if getline('.') =~# '^\s*pr$'
            execute "normal! Aintf(\"\\n\");\<esc>4h"
            startinsert
        elseif getline('.') =~# '^\s*pri$'
            execute "normal! Antf(\"value: %d\\n\", );\<esc>h"
            startinsert
        elseif getline('.') =~# '^\s*main$'
            execute "normal! ^d$i#include <stdio.h>\<cr>#include <stdlib.h>\<cr>\<cr>\<cr>int main(void)\<cr>{\<cr>puts(\"hello\");\<cr>return 0;\<cr>}\<esc>kk"
        else
            execute "normal! A**"
            startinsert!
        endif
    endfunction

    inoremap ** <esc>:call g:ExpandSnippet()<cr>

    " Preload register 's' in order to quickly sign patches with "sp
    let @s="Signed-off-by: Ilias Stamatis <stamatis.iliass@gmail.com>"
" }

" Languages {
    " Greek {
        set keymap=greek_utf-8
    " }

    " Easy change keymap.
    inoremap <leader>g <c-^>

    " Don't enable keymap by default in Insert mode and when entering a search pattern.
    set iminsert=0
    set imsearch=-1
" }

" Shell Command {
    " Display output of shell commands in new window.
    " Only one window by command, if a window already exists for a command, it will be reused.
    " E.g. :Shell ls
    function! s:ExecuteInShell(command, bang)
        let _ = a:bang != '' ? s:_ : a:command == '' ? '' : join(map(split(a:command), 'expand(v:val)'))

        if (_ != '')
            let s:_ = _
            let bufnr = bufnr('%')
            let winnr = bufwinnr('^' . _ . '$')
            silent! execute  winnr < 0 ? 'belowright new ' . fnameescape(_) : winnr . 'wincmd w'
            setlocal buftype=nowrite bufhidden=wipe nobuflisted noswapfile wrap number
            silent! :%d
            let message = 'Execute ' . _ . '...'
            call append(0, message)
            echo message
            silent! 2d | resize 1 | redraw
            silent! execute 'silent! %!'. _
            silent! execute 'resize ' . line('$')
            silent! execute 'syntax on'
            silent! execute 'autocmd BufUnload <buffer> execute bufwinnr(' . bufnr . ') . ''wincmd w'''
            silent! execute 'autocmd BufEnter <buffer> execute ''resize '' .  line(''$'')'
            silent! execute 'nnoremap <silent> <buffer> <cr> :call <SID>ExecuteInShell(''' . _ . ''', '''')<cr>'
            " Reexecute command with <localleader>r in a window opened by :Shell.
            silent! execute 'nnoremap <silent> <buffer> <LocalLeader>r :call <SID>ExecuteInShell(''' . _ . ''', '''')<cr>'
            " Go to the previous window with <localleader>g.
            silent! execute 'nnoremap <silent> <buffer> <LocalLeader>g :execute bufwinnr(' . bufnr . ') . ''wincmd w''<cr>'
            nnoremap <silent> <buffer> <C-W>_ :execute 'resize ' . line('$')<cr>
            silent! syntax on
        endif
    endfunction

    command! -complete=shellcmd -nargs=* -bang Shell call s:ExecuteInShell(<q-args>, '<bang>')
" }

" Plugins Configuration {
    " neocomplete {
        " Use neocomplete.
        let g:neocomplete#enable_at_startup = 1
        " Use smartcase.
        let g:neocomplete#enable_smart_case = 1
        " Set minimum syntax keyword length.
        let g:neocomplete#sources#syntax#min_keyword_length = 3

        " <TAB>: completion.
        inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
    " }

    " nerdcommenter {
        " Add spaces after comment delimiters by default
        let g:NERDSpaceDelims = 1

        " Use // style comments for C since nesting /* */ comments isn't legal
        let g:NERDCustomDelimiters = { 'c': { 'left': '//','right': '' } }
    " }

    " TagBar {
        set tags=./tags;/,~/.vimtags
        nnoremap <silent> <leader>tt :TagbarToggle<cr>
    " }
" }
