# .zshenv is always sourced first before .zprofile, .zshrc or any other file
# it is sourced independently of whether the shell is login, interactive, etc.

export DOTFILES="$HOME"/.dotfiles

export BROWSER=firefox

export EDITOR=vim
export VISUAL=vim
export PAGER=less

# in case we are on Fedora
if [ -f /var/log/dnf.log ]; then
    export EDITOR=vimx
    export VISUAL=vimx
fi
