# .zshenv is always sourced first before .zprofile, .zshrc or any other file
# it is sourced independently of whether the shell is login, interactive, etc.

# Use ISO date format
export LC_TIME=en_DK.UTF-8

export DOTFILES="$HOME"/.dotfiles

export BROWSER=firefox

export EDITOR=vim
export VISUAL=vim
export PAGER=less

if [ -f $HOME/.cargo/env ]; then
    source "$HOME/.cargo/env"
fi

# in case we are on Fedora
if [ -f /var/log/dnf.log ]; then
    export EDITOR=vimx
    export VISUAL=vimx
fi

export PYTHONSTARTUP=${DOTFILES}/misc/python.startup
