# oh-my-zsh configuration

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="mytheme"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

source $ZSH/oh-my-zsh.sh

# My configuration...

# Use vi key bindings
bindkey -v

# This feature is annoying sometimes. It corrects you, when you are trying to create new files, for example.
unsetopt correctall

# Print an empty line before the prompt is rendered.
precmd() { echo }

# Load aliases
source $DOTFILES/zsh/zsh_aliases
