# path to the oh-my-zsh installation
export ZSH=$HOME/.oh-my-zsh

# automatically update oh-my-zsh without prompting
DISABLE_UPDATE_PROMPT="true"

ZSH_THEME="mytheme" # must be in $ZSH/themes
source $ZSH/oh-my-zsh.sh

# print an empty line before the prompt is rendered
precmd() { echo }

# personal L4-related stuff
if [ -f ~/.l4stuff/l4_sh ]; then
    source ~/.l4stuff/l4_sh
fi
